<?php
/* Srolling:
 *  All = Todos
 *  Elastic = Igual do google
 *  Jumping = o numero vai avançando para o fim
 *  Sliding = igual o Yahoo (centraliza a página)
 *
 * $this->first = primeira página
 * $this->firstItemNumber = N° absoluto do primeiro item na página atual
 * $this->firstPageInRange = Primeira página no internavo retornado pelo estilo de srolling
 * $this->current = página atual
 * $this->last = última página
 * $this->lastItemNumber = Nº absoluto do último item nesta página
 * $this->lastPageInRange = última página no internavo retornado pelo estilo de srolling
 * $this->next = próxima página
 * $this->pageCount = número de páginas
 * $this->pagesInRange = Array de páginas retornado pelo estilo de scrolling
 * $this->previuos = página anterior
 * $this->totalItemCount = Número Total de itens
 */

if ($this->pageCount) {
    ?>
    <div id="paginator">
        <?php
        /* PRIMEIRA PAGINA */
        if (isset($this->previous)) :
            ?>
            <a href="<?php echo $this->url(array('page' => $this->first)); ?>">Primeira</a>
            <!-- <a href="/post/?page=1">Primeira</a> -->
            <!-- <a href="/post/?page=<?php echo $this->first ?>">Primeira</a> -->
            <?php
        endif;

        /* SETA < */
        if (isset($this->previous)) :
            ?>
            <a href="<?php echo $this->url(array('page' => $this->previous)); ?>"> < </a>
            <!-- <a href="/post/?page=<?php //echo $this->previous  ?>"> < </a> -->
            <?php
        endif;

        /* IMPRIME OS NUMEROS DA PAGINAÇÃO */
        foreach ($this->pagesInRange as $page) :

            if ($this->current == $page):
                ?>
                <strong class="current"><?php echo $page ?></strong>
                <?php
            else:
                ?>
                <a href="/post/?page=<?php echo $page ?>"><?php echo $page ?></a>
            <?php
            endif;
        endforeach;

        /* SETA > */
        if (isset($this->next)) {
            ?>
            <a href="<?php echo $this->url(array('page' => $this->next)) ?>"> > </a>
            <?php
        };
        
        /* ULTIMA PAGINA */
        if (isset($this->next)) {
            ?>
            <a href="<?php echo $this->url(array('page' => $this->last)) ?>"> Última </a>
        <?php }; ?>
    </div>
<?php }; ?>