
<?php
//$this->headTitle()->prepend('Ver'); 

/* TITULO DA PAGINA */
$this->headTitle()->append('Ver');

/* CSS ESPECIFICO DA PAGINA */
$this->headLink()->appendStylesheet('/css/index/ver.css');

/* JS ESPECIFICO DA PAGINA */
$this->headScript()->appendFile('/js/index/ver.js');
?>

<br /><br />
<div id="view-content">
    <p>View script for controller <b>Index</b> and script/action name <b>ver</b></p>
</div>

